org: enriquecellback
app: typeform-webhook-integration
service: typeform-webhook-integration
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
