org: usaseancouncil
app: typeform
service: typeform-webhook-integration

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
